SET CLIENT_ENCODING TO 'UTF8';

CREATE TABLE USER_INFO (
	EMAIL VARCHAR(50) NOT NULL,
	FEEDBACK BOOLEAN NOT NULL,
	FEEDBACK_ITERATION INTEGER NOT NULL,
	PRIMARY KEY (EMAIL)
);

CREATE TABLE TRIP_HISTORY (
	TRIP_HISTORY_ID SERIAL NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	ORIGIN_PLACE VARCHAR(100) NOT NULL,
	DESTINATION_PLACE VARCHAR(100) NOT NULL,
	TRIP_MODE VARCHAR(20) NOT NULL,
	FEEDBACK VARCHAR(1000),
	DISTANCE VARCHAR(1000),
	DURATION VARCHAR(1000),
	STATIC_MAP VARCHAR(1000),
	LINK VARCHAR(1000),
	CREATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (TRIP_HISTORY_ID),
	FOREIGN KEY (EMAIL) REFERENCES USER_INFO (EMAIL) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PLACE (
	PLACE_ID SERIAL NOT NULL,
	TRIP_HISTORY_ID SERIAL NOT NULL,
	NAME VARCHAR(1000) NOT NULL,
	WEBS VARCHAR(1000),
	PHONES VARCHAR(1000),
	HOURS VARCHAR(1000),
	ADDRESS VARCHAR(1000),
	MAIN_PLACE BOOLEAN NOT NULL,
	PRIMARY KEY (PLACE_ID),
	FOREIGN KEY (TRIP_HISTORY_ID) REFERENCES TRIP_HISTORY (TRIP_HISTORY_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE EMAIL_TEMPLATE (
	EMAIL_TEMPLATE_ID SERIAL NOT NULL,
	TEMPLATE VARCHAR(30000) NOT NULL,
	PLACE_NAME_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACE_HOURS_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACE_PHONE_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACE_WEB_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACE_ADDRESS_TEMPLATE VARCHAR(1000) NOT NULL,
	KM_TEMPLATE VARCHAR(1000) NOT NULL,
	TIME_TEMPLATE VARCHAR(1000) NOT NULL,
	STATIC_MAP_TEMPLATE VARCHAR(10000) NOT NULL,
	LINK_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACES_NAME_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACES_PHONE_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACES_WEB_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACES_HOURS_TEMPLATE VARCHAR(1000) NOT NULL,
	PLACES_TEMPLATE VARCHAR(10000) NOT NULL,
	PRIMARY KEY (EMAIL_TEMPLATE_ID)
)